### ISSUE TITLE
Calendar notifications appear although turned off

### ISSUE THREAD

**Issue by mayonezo** [nextcloud/notifications#1825]
### Steps to reproduce
1. Turn off calendar notifications (push & E-Mail)

### Expected behaviour
No notifications are sent

### Actual behaviour
Notifications are sent via push & E-Mail

### Server configuration

**Operating system**: Debian Bookworm

**Web server:** Apache2

**Database:** MariaDB

**PHP version:** 8.2

**Nextcloud version:** 28.0.2

**Where did you install Nextcloud from:** Manual install

**Signing status:**

```
No errors have been found.
```

**Comment by nickvergessen** [comment]
Check `index.php/settings/user/notifications`
Mostlikely you opted-in there somehow?

If that is off, it could be things that were scheduled before you changed the settings. Otherwise you'd need to post a screenshot of the push/email so we can move it to the correct repository, because this app here is just the "empty UI" and does not handle any notifications directly.

**Comment by mayonezo** [comment]
These are the settings for calender, contacts and tasks:

![Screenshot 2024-02-23 112146](https://github.com/nextcloud/notifications/assets/5090215/e7a2939e-915c-4eea-9db0-f6391022b0c8)

And this is a push notification I got:

![Screenshot_2024-02-20-08-44-06-172_org mozilla firefox](https://github.com/nextcloud/notifications/assets/5090215/08426823-6a8e-4995-9d87-a1e3c16291bb)

**Comment by mayonezo** [comment]
The event was created long after I turned off the notification settings.

**Comment by joshtrichards** [comment]
Sounds like nextcloud/server#40103

Go to *Administration settings->Groupware->Calendar Server* and toggle off the last option called "Enable notifications for events via push".
