### ISSUE TITLE
notification bell does not adapt to theme, always white

### ISSUE THREAD

**Issue by blizzz** [nextcloud/notifications#1962]
### Steps to reproduce
1. Run notifications from master
2. Have a background  that will have icons black, also dark mode
3. Look at the notification bell

### Expected behaviour

The bell is black

### Actual behaviour

It is an old, white bell

![Screenshot_20240628_221929](https://github.com/nextcloud/notifications/assets/2184312/6776bc46-bb82-4b40-9340-588b35fe9197)

This also happened after increasing the cachebuster, and also when switiching to light mode (all icons are black, but the bell)

I have not seen a similar bug report so far. Apologies if I oversaw one.

cc @Antreesy

**Comment by nickvergessen** [comment]
Can you share the image and the theming color?

**Comment by Antreesy** [comment]
Found related server change for 29, but it wasn't backported to main: https://github.com/nextcloud/server/pull/45430

UnifiedSearch and ContactsMenu have this internal style, Notifications App doesn't
```css
#header .header-menu__trigger-icon {
    color: var(--color-background-plain-text) !important;
}
```
Plain solution would be to add it, but whenever next change comes, we need to fix it again in three different places
So I'd say, should be fixed in vue-library? (cc @susnux )

**Comment by blizzz** [comment]
> Can you share the image and the theming color?

If still relevant, it is one of the shipped images:

![Screenshot_20240702_113540](https://github.com/nextcloud/notifications/assets/2184312/892b890f-1e73-4b77-88e9-8c23f8fbcaa9)

Dark mode (via system pref), and primary color is Nextcloud blue / #006789
