### ISSUE TITLE
More compact email notification design

### ISSUE THREAD

**Issue by helmo** [nextcloud/notifications#2101]
### How to use GitHub

* Please use the 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to show that you are interested into the same feature.
* Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
* Subscribe to receive notifications on status change and new comments.

---

## Feature request

I'd like to propose a more compact design for the email notifications that Nextcloud sends.

In my regular window size all relevant info is outside of the visible area.  It feels a bit wasteful of the screen real estate. And I prefer to not have to scroll to be able to read the message content.

I'm no designer, but I've used my best Gimp skills to create a mockup of what I think would be an improvement.

**Which Nextcloud Version are you currently using: 30.0.2

**Describe the solution you'd like**

Would be nice if the mail templates could be updated to have a more compact layout.

**Describe alternatives you've considered**

I could resize the window, but then it would be too big for most of the other mails.

**Additional context**

As it is now:
![Image](https://github.com/user-attachments/assets/947817f6-1379-4042-b1f4-0b4024a3c75c)

As I'd like to see it:
![Image](https://github.com/user-attachments/assets/bab2e656-c941-4d91-858c-0cc9a15fefa9)

**Comment by nickvergessen** [comment]
Thanks for your request. You can do that yourself already now using a custom email template as a workaround:
https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/email_configuration.html#using-email-templates

Within this app however we will not overwrite the email layout. So if this should be done, it would need to be done in a generic way directly in the server code. Can you create a new enhancement in https://github.com/nextcloud/server/issues/new?template=Feature_request.md

This allows to keep the issue here to have matching search results for others.
