### ISSUE TITLE
Can't see/expand whole notification

### ISSUE THREAD

**Issue by panyann** [nextcloud/notifications#814]
### Steps to reproduce
1. Use Nextcloud you dummy

### Expected behaviour
I should see whole notification or at least have a button to expand it.

### Actual behaviour
Notification is cut in half and can't be clicked.

### Server configuration
This is basically the snap version of Nextcloud.

**Operating system**:
Ubuntu Server

**Web server:**
Apache2

**Database:**
mysql 5.7.32

**PHP version:**
7.4.13

**Nextcloud version:** 20.0.2

**Where did you install Nextcloud from:**
snap

And I don't feel like filling all of that useless information from the issue template, the problem is simple and the installation has few days, so it's almost fresh install, you can basically check the snap configuration.

The problem:
![image](https://user-images.githubusercontent.com/22815508/100860832-4fe14e00-3491-11eb-84c5-bd476d6835c6.png)

I can't click on it or read the rest of the notification. That's all really there is to it. You advertise that as something which supports up to 4000 characters per notification...

**Comment by jancborchardt** [comment]
@panyann in the Nextcloud community, we communicate in a considerate, respectful and friendly manner.
When opening issues, keep in mind that everyone working on the project are humans too and much prefer a friendly environment rather than one were people are called dummy and requested info is described as useless.

For more info see our Code of Conduct https://nextcloud.com/contribute/code-of-conduct/ which is valid in all our offline and online spaces.

Thanks for being more considerate in the future.

**Comment by inthreedee** [comment]
Here is the code that generates this notification after each snap update:
https://github.com/nextcloud/nextcloud-snap/blob/e4f6821bf179cd675fe0a17e638a1646d5f54987/src/nextcloud/fixes/existing-install/99_notify_admins.sh#L9-L17

This capability was added as a way to notify admins if they must take manual action to address issues after an automatic update.  This particular notification is just the generic one, meaning no specific actions were necessary this time.

Regardless of the tone of the initial report, the issue does seem to be valid; I can confirm it on my end.
