### ISSUE TITLE
Add current notification count to document title

### ISSUE THREAD

**Issue by revpriest** [nextcloud/notifications#892]
I like the next-cloud app to be in a pinned tab in Firefox. Many apps get highlighted with a blue light when they have changed, EG a new notification or a new email arrived. 

Next cloud does not.

### Steps to reproduce
1. Pin tab in Firefox
2. Have a notification arrive
3. Observe the pinned tab does not hilight

### Expected behaviour
I would like the pinned tab to highlight when a notification arrives.

The notification appears when the document title changes.

Adding the current number of notifications to the document title would therefore make the pinned-tab changed-highlight work.

### Actual behaviour
The document title does not reflect the number of notifications.

The following patch does the work of making the notification-counts show up in the document title.

Presumably though some would prefer that it didn't, so it should have a setting somewhere? 

Where do we think would be best for such a setting?

I'd like to attach an emojii to each app/object_id instead of using the first two letters as it does here, but can't put the app svg images into the title description. Perhaps a setting should also allow associating an emojii with each object_id?

Just looking for some feedback on what kind of pull requests you might like for this.

[addNotifactionsToTitle.patch.txt](https://github.com/nextcloud/notifications/files/6151299/addNotifactionsToTitle.patch.txt)

Also would like the email app to send a notification for new emails, but one step at a time eh?

**Comment by nickvergessen** [comment]
The problem is this collides with several other apps that already do things like this. E.g. Talk is modifying the page title and prepending a symbol for unread messages and so on. With different things interacting on top of each others it will instead of being useful confuse users and make them unable to find the Nextcloud tab again because instead of "Files - Nextcloud" it now says "📆 Files - Next..." or something like that.

Also adding the number all the time can be pretty troublesome and stress producing when you are a heavy user as you get the feeling that you have to solve them right now. This is why Talk uses `* `  as a marker and when you visit the tab again it removes it again, independent whether you read it or not.
If we do something like this for notifications, I would reuse the pattern, that is:
* Prepend `* ` when the notification count increases and the tab is not active
* Remove `* ` when the tab is active again

**Comment by revpriest** [comment]
Yes, I was looking to see if there was any kind of general title-managing system. That would be ideal but I guess none is planned, let alone immiment?

A * instead of count is fine.

**Comment by nickvergessen** [comment]
No sadly not, ref is:
* https://github.com/nextcloud/spreed/blob/master/src/App.vue#L378
* https://github.com/nextcloud/spreed/blob/master/src/App.vue#L356
* https://github.com/nextcloud/spreed/blob/master/src/App.vue#L178

**Comment by revpriest** [comment]
Hope that's good, let me know if you want any changes. Thanks for your review :)

**Comment by revpriest** [comment]
Oh. Still failing. Does that means that js/notifications-main.js and js/notifications-main.js.map should be in the pull request too then? Surprising, figured it'd only need files I actually changed.
